version: 2.1

orbs:
  docker: circleci/docker@1.7.0
  gcp-cloud-run: circleci/gcp-cloud-run@1.0.2
  

workflows:
    docker-build:
      jobs:
        # - docker/publish:
        #     lint-dockerfile: true 
        #     docker-password: DOCKER_PASSWORD 
        #     docker-username: DOCKER_USERNAME 
        #     dockerfile: Dockerfile 
        #     tag: latest
        #     image: keresifon/gke
        - kuber
            #  requires:
            #    - "docker/publish"
        




jobs:
  kuber:
    docker:
      # replace with your preferred image
      - image: keresifon/gke:latest
    steps:
      #  - checkout 
       - run:
          command:  apt install curl
       - gcp-cloud-run/init:
          gcloud-service-key: GCLOUD_SERVICE_KEY 
          google-compute-zone: GOOGLE_COMPUTE_ZONE 
          google-project-id: GOOGLE_PROJECT_ID 
      #  - run:
      #     command: | 
      #         kubectl apply -f kubernetes/namespace.yaml
      #         kubectl apply -f kubernetes/service.yaml
      #         kubectl apply -f kubernetes/ingress.yaml
      #         kubectl delete -f kubernetes/deployment.yaml
      #         kubectl apply -f kubernetes/deployment.yaml

