version: 2.1

orbs:

  docker: circleci/docker@1.7.0
  aws-eks: circleci/aws-eks@1.1.0
  

workflows:
  docker-build:
    jobs:
      # - docker/publish:
      #     lint-dockerfile: true
      #     docker-password: DOCKER_PASSWORD
      #     docker-username: DOCKER_USERNAME
      #     dockerfile: Dockerfile
      #     tag: latest
      #     image: keresifon/eks
      - aws
          # requires:
          #   - "docker/publish"
      
 
      

jobs:
  # kuber:
  #   docker:
  #     - image: keresifon/eks:latest
  #   steps:
  #     - checkout
  #     - run:
  #         command: |
  #           apt-get update
  #           apt-get -qq -y install curl
  #           apt-get install -y python
  #           apt-get install -y gnupg
  #           curl -O https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
  #           bash ./get-helm-3
  aws:
    docker:
      - image: keresifon/eks:latest
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          install-kubectl: true 
          cluster-name: portfolio-eks-ITFEs2sZ 
          cluster-authentication-role-arn: arn:aws:iam::870899748481:user/kereawsd 
          aws-profile: kereawsd 
          aws-region: us-east-1 

     
      
