version: 2.1

orbs:
  docker: circleci/docker@1.7.0

workflows:
    docker-build:
      jobs:
        - docker/publish:
            lint-dockerfile: true 
            docker-password: DOCKER_PASSWORD 
            docker-username: DOCKER_USERNAME 
            dockerfile: Dockerfile 
            image: keresifon/circle-ci 