version: 2.1

orbs:
  docker: circleci/docker@1.7.0
  k8s: digitalocean/k8s@0.1.1
  kubernetes: circleci/kubernetes@0.12.0
  

workflows:
    docker-build:
      jobs:
        - docker/publish:
            lint-dockerfile: true 
            docker-password: DOCKER_PASSWORD 
            docker-username: DOCKER_USERNAME 
            dockerfile: Dockerfile 
            tag: latest
            image: keresifon/circle-ci 
        - kuber:
             requires:
               - "docker/publish"
        - deploy:
             requires:
               - "kuber"




jobs:
  kuber:
    docker:
      # replace with your preferred image
      - image: keresifon/circle-ci:latest
    steps:
       - k8s/install
       - k8s/initialize:
          cluster: kere 
          digitalocean-access-token: DIGITALOCEAN_ACCESS_TOKEN 


  deploy:
    docker:
      # replace with your preferred image
      - image: keresifon/circle-ci:latest
    steps:
      - kubernetes/create-or-update-resource:
          action-type: apply 
          resource-file-path: /p.yaml 
          show-kubectl-command: true 