version: 2.1

orbs:
  docker: circleci/docker@1.7.0
  k8s: digitalocean/k8s@0.1.1

workflows:
    docker-build:
      jobs:
        - docker/publish:
            lint-dockerfile: true 
            docker-password: DOCKER_PASSWORD 
            docker-username: DOCKER_USERNAME 
            dockerfile: Dockerfile 
            tag: latest
            image: keresifon/circle-ci 

    kubernetes-deploy:
      jobs:
        - description: Initialize kubeconfig to connect to DigitalOcean Kubernetes Engine
        - parameters:
            cluster:
              description: The Kubernetes cluster name.
              type: string
            digitalocean-access-token:
              default: DIGITALOCEAN_ACCESS_TOKEN
              description: The access token to connect DigitalOcean
              #type: env_var_name
        - steps:
            doctl/initialize:
            digitalocean-access-token: DIGITALOCEAN_ACCESS_TOKEN
            
      


  