version: 2.1

orbs:
  docker: circleci/docker@1.7.0

workflows:
    docker-build:
      jobs:
        - docker/publish:
            lint-dockerfile: true 
            docker-password: DOCKER_PASSWORD 
            docker-username: DOCKER_USERNAME 
            dockerfile: Dockerfile 
            tag: latest
            image: keresifon/circle-ci 

    kubernetes-deploy:
      jobs:
        - docker:
           image: keresifon/circle-ci:latest
    
        - k8s/initialize:
              digitalocean-access-token: DIGITALOCEAN_ACCESS_TOKEN 
              cluster: portfolio 


  