version: 2.1

orbs:

  docker: circleci/docker@1.7.0
  aws-eks: frameio/aws-eks@0.24.0
  

workflows:
  docker-build:
    jobs:
      - docker/publish:
          lint-dockerfile: true
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_USERNAME
          dockerfile: Dockerfile
          tag: latest
          image: keresifon/eks
      - kuber:
          requires:
            - "docker/publish"
      - aws:
         requires:
           - "kuber"
 
      

jobs:
  kuber:
    docker:
      - image: keresifon/eks:latest
    steps:
      - checkout
      - run:
          command: |
            apt-get update
            apt-get -qq -y install curl
            apt-get install -y python
            apt-get install -y gnupg
            curl -O https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
            bash ./get-helm-3
  aws:
    docker:
      - image: keresifon/eks:latest
    steps:
      - checkout
      - aws-eks/login:
          cluster: portfolio-eks-ITFEs2sZ 
          region: us-east-1 

     
      
